FROM golang:1.8

WORKDIR /go/src
COPY ./Godeps /go/src
COPY ./compile.sh /go/src

RUN apt-get update && apt-get install wget
RUN wget https://raw.githubusercontent.com/pote/gpm/v1.4.0/bin/gpm && chmod +x gpm && mv gpm /usr/local/bin
RUN gpm install
RUN cp -r ./github.com /github.com  # backup packages to root to prevent volume mount removing it

CMD ["./compile.sh"]
